[workspace]
resolver = "2"

members = [
    "vhost",
    "vhost-user-backend",
]

[workspace.dependencies]
virtio-bindings = "0.2.1"
virtio-queue = { git = "https://github.com/rust-vmm/vm-virtio.git", branch = "main" }
vm-memory = "0.16.0"
vmm-sys-util = "0.12.1"
