[workspace]
resolver = "2"

members = [
    "vhost",
    "vhost-user-backend",
]

[workspace.dependencies]
virtio-bindings = "0.2.5"
virtio-queue = "0.15.0"
vm-memory = "0.16.2"
vmm-sys-util = { git = "https://github.com/uran0sH/vmm-sys-util", branch = "event-abstract" }
